// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RatSim.proto
#ifndef GRPC_RatSim_2eproto__INCLUDED
#define GRPC_RatSim_2eproto__INCLUDED

#include "RatSim.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace RatSim {

// Services:
class LidarService final {
 public:
  static constexpr char const* service_full_name() {
    return "RatSim.LidarService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::LidarData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarData>> AsyncGetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarData>>(AsyncGetLiDARDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarData>> PrepareAsyncGetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarData>>(PrepareAsyncGetLiDARDataRaw(context, request, cq));
    }
    virtual ::grpc::Status GetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::Odometry* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>> AsyncGetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>>(AsyncGetLiDAROdomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>> PrepareAsyncGetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>>(PrepareAsyncGetLiDAROdomRaw(context, request, cq));
    }
    virtual ::grpc::Status GetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::LidarDataAndOdom* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarDataAndOdom>> AsyncGetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarDataAndOdom>>(AsyncGetLiDARDataAndOdomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarDataAndOdom>> PrepareAsyncGetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarDataAndOdom>>(PrepareAsyncGetLiDARDataAndOdomRaw(context, request, cq));
    }
    virtual ::grpc::Status SendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::RatSim::Status* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>> AsyncSendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>>(AsyncSendPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>> PrepareAsyncSendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>>(PrepareAsyncSendPointsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarDataAndOdom* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarDataAndOdom* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData* request, ::RatSim::Status* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData* request, ::RatSim::Status* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarData>* AsyncGetLiDARDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarData>* PrepareAsyncGetLiDARDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>* AsyncGetLiDAROdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>* PrepareAsyncGetLiDAROdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarDataAndOdom>* AsyncGetLiDARDataAndOdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::LidarDataAndOdom>* PrepareAsyncGetLiDARDataAndOdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>* AsyncSendPointsRaw(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>* PrepareAsyncSendPointsRaw(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::LidarData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::LidarData>> AsyncGetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::LidarData>>(AsyncGetLiDARDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::LidarData>> PrepareAsyncGetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::LidarData>>(PrepareAsyncGetLiDARDataRaw(context, request, cq));
    }
    ::grpc::Status GetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::Odometry* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>> AsyncGetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>>(AsyncGetLiDAROdomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>> PrepareAsyncGetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>>(PrepareAsyncGetLiDAROdomRaw(context, request, cq));
    }
    ::grpc::Status GetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::LidarDataAndOdom* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::LidarDataAndOdom>> AsyncGetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::LidarDataAndOdom>>(AsyncGetLiDARDataAndOdomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::LidarDataAndOdom>> PrepareAsyncGetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::LidarDataAndOdom>>(PrepareAsyncGetLiDARDataAndOdomRaw(context, request, cq));
    }
    ::grpc::Status SendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::RatSim::Status* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Status>> AsyncSendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Status>>(AsyncSendPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Status>> PrepareAsyncSendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Status>>(PrepareAsyncSendPointsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarData* response, std::function<void(::grpc::Status)>) override;
      void GetLiDARData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarData* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response, std::function<void(::grpc::Status)>) override;
      void GetLiDAROdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarDataAndOdom* response, std::function<void(::grpc::Status)>) override;
      void GetLiDARDataAndOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarDataAndOdom* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData* request, ::RatSim::Status* response, std::function<void(::grpc::Status)>) override;
      void SendPoints(::grpc::ClientContext* context, const ::RatSim::LidarData* request, ::RatSim::Status* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::RatSim::LidarData>* AsyncGetLiDARDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::LidarData>* PrepareAsyncGetLiDARDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>* AsyncGetLiDAROdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>* PrepareAsyncGetLiDAROdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::LidarDataAndOdom>* AsyncGetLiDARDataAndOdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::LidarDataAndOdom>* PrepareAsyncGetLiDARDataAndOdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::Status>* AsyncSendPointsRaw(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::Status>* PrepareAsyncSendPointsRaw(::grpc::ClientContext* context, const ::RatSim::LidarData& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetLiDARData_;
    const ::grpc::internal::RpcMethod rpcmethod_GetLiDAROdom_;
    const ::grpc::internal::RpcMethod rpcmethod_GetLiDARDataAndOdom_;
    const ::grpc::internal::RpcMethod rpcmethod_SendPoints_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetLiDARData(::grpc::ServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarData* response);
    virtual ::grpc::Status GetLiDAROdom(::grpc::ServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response);
    virtual ::grpc::Status GetLiDARDataAndOdom(::grpc::ServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarDataAndOdom* response);
    virtual ::grpc::Status SendPoints(::grpc::ServerContext* context, const ::RatSim::LidarData* request, ::RatSim::Status* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetLiDARData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetLiDARData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetLiDARData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLiDARData(::grpc::ServerContext* context, ::RatSim::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::RatSim::LidarData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetLiDAROdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetLiDAROdom() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetLiDAROdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDAROdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLiDAROdom(::grpc::ServerContext* context, ::RatSim::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::RatSim::Odometry>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetLiDARDataAndOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetLiDARDataAndOdom() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetLiDARDataAndOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARDataAndOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarDataAndOdom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLiDARDataAndOdom(::grpc::ServerContext* context, ::RatSim::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::RatSim::LidarDataAndOdom>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendPoints() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_SendPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPoints(::grpc::ServerContext* /*context*/, const ::RatSim::LidarData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPoints(::grpc::ServerContext* context, ::RatSim::LidarData* request, ::grpc::ServerAsyncResponseWriter< ::RatSim::Status>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetLiDARData<WithAsyncMethod_GetLiDAROdom<WithAsyncMethod_GetLiDARDataAndOdom<WithAsyncMethod_SendPoints<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetLiDARData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetLiDARData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::LidarData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarData* response) { return this->GetLiDARData(context, request, response); }));}
    void SetMessageAllocatorFor_GetLiDARData(
        ::grpc::MessageAllocator< ::RatSim::EmptyRequest, ::RatSim::LidarData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::LidarData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetLiDARData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLiDARData(
      ::grpc::CallbackServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarData* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetLiDAROdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetLiDAROdom() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::Odometry>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response) { return this->GetLiDAROdom(context, request, response); }));}
    void SetMessageAllocatorFor_GetLiDAROdom(
        ::grpc::MessageAllocator< ::RatSim::EmptyRequest, ::RatSim::Odometry>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::Odometry>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetLiDAROdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDAROdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLiDAROdom(
      ::grpc::CallbackServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetLiDARDataAndOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetLiDARDataAndOdom() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::LidarDataAndOdom>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::LidarDataAndOdom* response) { return this->GetLiDARDataAndOdom(context, request, response); }));}
    void SetMessageAllocatorFor_GetLiDARDataAndOdom(
        ::grpc::MessageAllocator< ::RatSim::EmptyRequest, ::RatSim::LidarDataAndOdom>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::LidarDataAndOdom>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetLiDARDataAndOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARDataAndOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarDataAndOdom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLiDARDataAndOdom(
      ::grpc::CallbackServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarDataAndOdom* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendPoints() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::RatSim::LidarData, ::RatSim::Status>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RatSim::LidarData* request, ::RatSim::Status* response) { return this->SendPoints(context, request, response); }));}
    void SetMessageAllocatorFor_SendPoints(
        ::grpc::MessageAllocator< ::RatSim::LidarData, ::RatSim::Status>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RatSim::LidarData, ::RatSim::Status>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPoints(::grpc::ServerContext* /*context*/, const ::RatSim::LidarData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::RatSim::LidarData* /*request*/, ::RatSim::Status* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetLiDARData<WithCallbackMethod_GetLiDAROdom<WithCallbackMethod_GetLiDARDataAndOdom<WithCallbackMethod_SendPoints<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetLiDARData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetLiDARData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetLiDARData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetLiDAROdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetLiDAROdom() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetLiDAROdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDAROdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetLiDARDataAndOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetLiDARDataAndOdom() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetLiDARDataAndOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARDataAndOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarDataAndOdom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendPoints() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_SendPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPoints(::grpc::ServerContext* /*context*/, const ::RatSim::LidarData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetLiDARData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetLiDARData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetLiDARData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLiDARData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetLiDAROdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetLiDAROdom() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetLiDAROdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDAROdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLiDAROdom(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetLiDARDataAndOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetLiDARDataAndOdom() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetLiDARDataAndOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARDataAndOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarDataAndOdom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLiDARDataAndOdom(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendPoints() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_SendPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPoints(::grpc::ServerContext* /*context*/, const ::RatSim::LidarData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPoints(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetLiDARData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetLiDARData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetLiDARData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetLiDARData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLiDARData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetLiDAROdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetLiDAROdom() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetLiDAROdom(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetLiDAROdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDAROdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLiDAROdom(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetLiDARDataAndOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetLiDARDataAndOdom() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetLiDARDataAndOdom(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetLiDARDataAndOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLiDARDataAndOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarDataAndOdom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLiDARDataAndOdom(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendPoints() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendPoints(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPoints(::grpc::ServerContext* /*context*/, const ::RatSim::LidarData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetLiDARData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetLiDARData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RatSim::EmptyRequest, ::RatSim::LidarData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RatSim::EmptyRequest, ::RatSim::LidarData>* streamer) {
                       return this->StreamedGetLiDARData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetLiDARData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetLiDARData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetLiDARData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RatSim::EmptyRequest,::RatSim::LidarData>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetLiDAROdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetLiDAROdom() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RatSim::EmptyRequest, ::RatSim::Odometry>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RatSim::EmptyRequest, ::RatSim::Odometry>* streamer) {
                       return this->StreamedGetLiDAROdom(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetLiDAROdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetLiDAROdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetLiDAROdom(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RatSim::EmptyRequest,::RatSim::Odometry>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetLiDARDataAndOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetLiDARDataAndOdom() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RatSim::EmptyRequest, ::RatSim::LidarDataAndOdom>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RatSim::EmptyRequest, ::RatSim::LidarDataAndOdom>* streamer) {
                       return this->StreamedGetLiDARDataAndOdom(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetLiDARDataAndOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetLiDARDataAndOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::LidarDataAndOdom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetLiDARDataAndOdom(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RatSim::EmptyRequest,::RatSim::LidarDataAndOdom>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendPoints() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RatSim::LidarData, ::RatSim::Status>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RatSim::LidarData, ::RatSim::Status>* streamer) {
                       return this->StreamedSendPoints(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendPoints(::grpc::ServerContext* /*context*/, const ::RatSim::LidarData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendPoints(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RatSim::LidarData,::RatSim::Status>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetLiDARData<WithStreamedUnaryMethod_GetLiDAROdom<WithStreamedUnaryMethod_GetLiDARDataAndOdom<WithStreamedUnaryMethod_SendPoints<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetLiDARData<WithStreamedUnaryMethod_GetLiDAROdom<WithStreamedUnaryMethod_GetLiDARDataAndOdom<WithStreamedUnaryMethod_SendPoints<Service > > > > StreamedService;
};

class MeshService final {
 public:
  static constexpr char const* service_full_name() {
    return "RatSim.MeshService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::RatSim::Status* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>> AsyncSendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>>(AsyncSendMeshRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>> PrepareAsyncSendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>>(PrepareAsyncSendMeshRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData* request, ::RatSim::Status* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData* request, ::RatSim::Status* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>* AsyncSendMeshRaw(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Status>* PrepareAsyncSendMeshRaw(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::RatSim::Status* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Status>> AsyncSendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Status>>(AsyncSendMeshRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Status>> PrepareAsyncSendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Status>>(PrepareAsyncSendMeshRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData* request, ::RatSim::Status* response, std::function<void(::grpc::Status)>) override;
      void SendMesh(::grpc::ClientContext* context, const ::RatSim::MeshData* request, ::RatSim::Status* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::RatSim::Status>* AsyncSendMeshRaw(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::Status>* PrepareAsyncSendMeshRaw(::grpc::ClientContext* context, const ::RatSim::MeshData& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendMesh_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendMesh(::grpc::ServerContext* context, const ::RatSim::MeshData* request, ::RatSim::Status* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendMesh() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMesh(::grpc::ServerContext* /*context*/, const ::RatSim::MeshData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendMesh(::grpc::ServerContext* context, ::RatSim::MeshData* request, ::grpc::ServerAsyncResponseWriter< ::RatSim::Status>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendMesh<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendMesh() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::RatSim::MeshData, ::RatSim::Status>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RatSim::MeshData* request, ::RatSim::Status* response) { return this->SendMesh(context, request, response); }));}
    void SetMessageAllocatorFor_SendMesh(
        ::grpc::MessageAllocator< ::RatSim::MeshData, ::RatSim::Status>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RatSim::MeshData, ::RatSim::Status>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMesh(::grpc::ServerContext* /*context*/, const ::RatSim::MeshData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendMesh(
      ::grpc::CallbackServerContext* /*context*/, const ::RatSim::MeshData* /*request*/, ::RatSim::Status* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendMesh<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendMesh() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMesh(::grpc::ServerContext* /*context*/, const ::RatSim::MeshData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendMesh() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMesh(::grpc::ServerContext* /*context*/, const ::RatSim::MeshData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendMesh(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendMesh() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendMesh(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMesh(::grpc::ServerContext* /*context*/, const ::RatSim::MeshData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendMesh(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendMesh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendMesh() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RatSim::MeshData, ::RatSim::Status>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RatSim::MeshData, ::RatSim::Status>* streamer) {
                       return this->StreamedSendMesh(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendMesh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendMesh(::grpc::ServerContext* /*context*/, const ::RatSim::MeshData* /*request*/, ::RatSim::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendMesh(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RatSim::MeshData,::RatSim::Status>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendMesh<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendMesh<Service > StreamedService;
};

class DepthCameraService final {
 public:
  static constexpr char const* service_full_name() {
    return "RatSim.DepthCameraService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::DepthCameraPointData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraPointData>> AsyncGetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraPointData>>(AsyncGetDepthCameraPointDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraPointData>> PrepareAsyncGetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraPointData>>(PrepareAsyncGetDepthCameraPointDataRaw(context, request, cq));
    }
    virtual ::grpc::Status GetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::DepthCameraImageData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraImageData>> AsyncGetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraImageData>>(AsyncGetDepthCameraImageDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraImageData>> PrepareAsyncGetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraImageData>>(PrepareAsyncGetDepthCameraImageDataRaw(context, request, cq));
    }
    virtual ::grpc::Status GetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::Odometry* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>> AsyncGetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>>(AsyncGetDepthCameraOdomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>> PrepareAsyncGetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>>(PrepareAsyncGetDepthCameraOdomRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraPointData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraPointData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraImageData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraImageData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraPointData>* AsyncGetDepthCameraPointDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraPointData>* PrepareAsyncGetDepthCameraPointDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraImageData>* AsyncGetDepthCameraImageDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::DepthCameraImageData>* PrepareAsyncGetDepthCameraImageDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>* AsyncGetDepthCameraOdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RatSim::Odometry>* PrepareAsyncGetDepthCameraOdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::DepthCameraPointData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraPointData>> AsyncGetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraPointData>>(AsyncGetDepthCameraPointDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraPointData>> PrepareAsyncGetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraPointData>>(PrepareAsyncGetDepthCameraPointDataRaw(context, request, cq));
    }
    ::grpc::Status GetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::DepthCameraImageData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraImageData>> AsyncGetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraImageData>>(AsyncGetDepthCameraImageDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraImageData>> PrepareAsyncGetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraImageData>>(PrepareAsyncGetDepthCameraImageDataRaw(context, request, cq));
    }
    ::grpc::Status GetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::RatSim::Odometry* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>> AsyncGetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>>(AsyncGetDepthCameraOdomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>> PrepareAsyncGetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>>(PrepareAsyncGetDepthCameraOdomRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraPointData* response, std::function<void(::grpc::Status)>) override;
      void GetDepthCameraPointData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraPointData* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraImageData* response, std::function<void(::grpc::Status)>) override;
      void GetDepthCameraImageData(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraImageData* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response, std::function<void(::grpc::Status)>) override;
      void GetDepthCameraOdom(::grpc::ClientContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraPointData>* AsyncGetDepthCameraPointDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraPointData>* PrepareAsyncGetDepthCameraPointDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraImageData>* AsyncGetDepthCameraImageDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::DepthCameraImageData>* PrepareAsyncGetDepthCameraImageDataRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>* AsyncGetDepthCameraOdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RatSim::Odometry>* PrepareAsyncGetDepthCameraOdomRaw(::grpc::ClientContext* context, const ::RatSim::EmptyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetDepthCameraPointData_;
    const ::grpc::internal::RpcMethod rpcmethod_GetDepthCameraImageData_;
    const ::grpc::internal::RpcMethod rpcmethod_GetDepthCameraOdom_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetDepthCameraPointData(::grpc::ServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraPointData* response);
    virtual ::grpc::Status GetDepthCameraImageData(::grpc::ServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraImageData* response);
    virtual ::grpc::Status GetDepthCameraOdom(::grpc::ServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDepthCameraPointData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDepthCameraPointData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetDepthCameraPointData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraPointData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraPointData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDepthCameraPointData(::grpc::ServerContext* context, ::RatSim::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::RatSim::DepthCameraPointData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDepthCameraImageData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDepthCameraImageData() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetDepthCameraImageData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraImageData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDepthCameraImageData(::grpc::ServerContext* context, ::RatSim::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::RatSim::DepthCameraImageData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDepthCameraOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDepthCameraOdom() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetDepthCameraOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDepthCameraOdom(::grpc::ServerContext* context, ::RatSim::EmptyRequest* request, ::grpc::ServerAsyncResponseWriter< ::RatSim::Odometry>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetDepthCameraPointData<WithAsyncMethod_GetDepthCameraImageData<WithAsyncMethod_GetDepthCameraOdom<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetDepthCameraPointData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetDepthCameraPointData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::DepthCameraPointData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraPointData* response) { return this->GetDepthCameraPointData(context, request, response); }));}
    void SetMessageAllocatorFor_GetDepthCameraPointData(
        ::grpc::MessageAllocator< ::RatSim::EmptyRequest, ::RatSim::DepthCameraPointData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::DepthCameraPointData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetDepthCameraPointData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraPointData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraPointData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDepthCameraPointData(
      ::grpc::CallbackServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraPointData* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetDepthCameraImageData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetDepthCameraImageData() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::DepthCameraImageData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::DepthCameraImageData* response) { return this->GetDepthCameraImageData(context, request, response); }));}
    void SetMessageAllocatorFor_GetDepthCameraImageData(
        ::grpc::MessageAllocator< ::RatSim::EmptyRequest, ::RatSim::DepthCameraImageData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::DepthCameraImageData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetDepthCameraImageData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraImageData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDepthCameraImageData(
      ::grpc::CallbackServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraImageData* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetDepthCameraOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetDepthCameraOdom() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::Odometry>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RatSim::EmptyRequest* request, ::RatSim::Odometry* response) { return this->GetDepthCameraOdom(context, request, response); }));}
    void SetMessageAllocatorFor_GetDepthCameraOdom(
        ::grpc::MessageAllocator< ::RatSim::EmptyRequest, ::RatSim::Odometry>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RatSim::EmptyRequest, ::RatSim::Odometry>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetDepthCameraOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDepthCameraOdom(
      ::grpc::CallbackServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetDepthCameraPointData<WithCallbackMethod_GetDepthCameraImageData<WithCallbackMethod_GetDepthCameraOdom<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetDepthCameraPointData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDepthCameraPointData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetDepthCameraPointData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraPointData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraPointData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetDepthCameraImageData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDepthCameraImageData() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetDepthCameraImageData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraImageData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetDepthCameraOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDepthCameraOdom() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetDepthCameraOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDepthCameraPointData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDepthCameraPointData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetDepthCameraPointData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraPointData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraPointData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDepthCameraPointData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDepthCameraImageData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDepthCameraImageData() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetDepthCameraImageData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraImageData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDepthCameraImageData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDepthCameraOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDepthCameraOdom() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetDepthCameraOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDepthCameraOdom(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetDepthCameraPointData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetDepthCameraPointData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDepthCameraPointData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetDepthCameraPointData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraPointData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraPointData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDepthCameraPointData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetDepthCameraImageData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetDepthCameraImageData() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDepthCameraImageData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetDepthCameraImageData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraImageData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDepthCameraImageData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetDepthCameraOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetDepthCameraOdom() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDepthCameraOdom(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetDepthCameraOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDepthCameraOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDepthCameraOdom(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDepthCameraPointData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDepthCameraPointData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RatSim::EmptyRequest, ::RatSim::DepthCameraPointData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RatSim::EmptyRequest, ::RatSim::DepthCameraPointData>* streamer) {
                       return this->StreamedGetDepthCameraPointData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDepthCameraPointData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDepthCameraPointData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraPointData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDepthCameraPointData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RatSim::EmptyRequest,::RatSim::DepthCameraPointData>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDepthCameraImageData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDepthCameraImageData() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RatSim::EmptyRequest, ::RatSim::DepthCameraImageData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RatSim::EmptyRequest, ::RatSim::DepthCameraImageData>* streamer) {
                       return this->StreamedGetDepthCameraImageData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDepthCameraImageData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDepthCameraImageData(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::DepthCameraImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDepthCameraImageData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RatSim::EmptyRequest,::RatSim::DepthCameraImageData>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDepthCameraOdom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDepthCameraOdom() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RatSim::EmptyRequest, ::RatSim::Odometry>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RatSim::EmptyRequest, ::RatSim::Odometry>* streamer) {
                       return this->StreamedGetDepthCameraOdom(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDepthCameraOdom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDepthCameraOdom(::grpc::ServerContext* /*context*/, const ::RatSim::EmptyRequest* /*request*/, ::RatSim::Odometry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDepthCameraOdom(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RatSim::EmptyRequest,::RatSim::Odometry>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetDepthCameraPointData<WithStreamedUnaryMethod_GetDepthCameraImageData<WithStreamedUnaryMethod_GetDepthCameraOdom<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetDepthCameraPointData<WithStreamedUnaryMethod_GetDepthCameraImageData<WithStreamedUnaryMethod_GetDepthCameraOdom<Service > > > StreamedService;
};

}  // namespace RatSim


#endif  // GRPC_RatSim_2eproto__INCLUDED
